Add automatic parameter tuning based on minimum cross-entropy thresholding
AdaptiveParticles/LibAPR pull request #151
Opened 2021-05-25 15:35 UTC by joeljonsson

Adds a new method to automatically compute thresholds for the gradient and local intensity scale using Li's iterative Minimum Cross Entropy algorithm ([https://doi.org/10.1016/S0167-8655(98)00057-9](https://doi.org/10.1016/S0167-8655(98)00057-9)). 

The thresholding method is applied only to gradient / intensity scale values where the image intensity exceeds the intensity threshold. This allows handling some difficult cases, e.g. where there are significant regions of background with and without autofluorescence, by manually setting the intensity threshold to an appropriate value.

I have tested this on a number of datasets, and it seems to mostly work very well. Would appreciate some further testing and feedback on this.

2021-05-25 19:29 UTC, cheesema commented
Where did the inspiration come from?

2021-05-27 09:50 UTC, joeljonsson commented
> Where did the inspiration come from?

Figured this was long overdue. I just tested any (simple) histogram thresholding method I could find via Python and this one consistently gave good results

2021-06-11 16:19 UTC, cheesema requested changes
Added some comments, does this work well in all dimensions? have you done any tests on 1D + 2D?

And sorry for taking so long :(

2021-06-11 16:19 UTC, cheesema commented on src/algorithm/APRConverter.hpp
> +    par.grad_th = threshold_li(grad_subsampled);
This par object is taken directly from the class, then we have also one where we are adding to the APR? Maybe we should remove the one from the class itself, and have this function work in a more static way so its more useful in the future? Would require changing of the signiture.

2021-06-11 16:19 UTC, cheesema commented on src/algorithm/APRConverter.hpp
> +    std::cout << "lambda: " << par.lambda << std::endl;
Should we remove this, or make this linked to a verbose flag of some kind?

2021-06-11 16:19 UTC, cheesema commented on src/algorithm/APRConverter.hpp
> +        const size_t num_elements = std::min((size_t)32*512*512, counter);
Where do these magic numbers come from?

2021-06-11 16:19 UTC, cheesema commented on src/algorithm/APRConverter.hpp
>      if( par.auto_parameters ) {
Would we then put this as default to true?

2021-06-14 10:15 UTC, joeljonsson commented on src/algorithm/APRConverter.hpp
> +    par.grad_th = threshold_li(grad_subsampled);
All converter methods (should) use the parameters instance of the converter class. The instance in the APR class is mainly there to save the used parameters. But I agree it's slightly confusing...

I can make the function take a parameters object as input, but removing the parameters instance from the converter class would require some refactoring. This would also induce breaking changes, as instead of setting the converter parameters before conversion one would have to either a) set the parameters of the APR object, or b) input a parameters object to all converter methods.

2021-06-14 11:15 UTC, joeljonsson commented on src/algorithm/APRConverter.hpp
> +    std::cout << "lambda: " << par.lambda << std::endl;
yup! this is done now

2021-06-14 11:19 UTC, joeljonsson commented on src/algorithm/APRConverter.hpp
> +        const size_t num_elements = std::min((size_t)32*512*512, counter);
Completely arbitrary. Perhaps it would make more sense to use a fraction of the image size?

2021-06-14 11:47 UTC, joeljonsson commented on src/algorithm/APRConverter.hpp
>      if( par.auto_parameters ) {
I'm not sure, as this would require explicitly turning it off every time you want to set your own values. Perhaps we can automatically turn it on based on some default values (e.g. -1) of `sigma_th` and `grad_th`? This could also allow some more flexibility in terms of which parameters are computed

2021-06-19 11:54 UTC, cheesema commented on src/algorithm/APRConverter.hpp
> +    par.grad_th = threshold_li(grad_subsampled);
Fair enough agreed.

2021-06-19 12:22 UTC, cheesema commented on src/algorithm/APRConverter.hpp
> +        const size_t num_elements = std::min((size_t)32*512*512, counter);
I think this is fine for now, you use the random subsampling.

2021-06-19 12:23 UTC, cheesema commented
Everything is good from my side, I added a few minor changes for you to look at, after that feel free to merge.

2021-06-19 12:24 UTC, cheesema approved these changes

2021-06-21 08:34 UTC, merged