Expand lazy functionality
AdaptiveParticles/LibAPR pull request #160
Opened 2021-11-13 20:45 UTC by joeljonsson

Adds `LazyAccess` and `LazyIterator` classes, as well as a lazy (patch) reconstruction function.

Additional lazy functionality can easily be added following a similar recipe.

2021-11-16 10:28 UTC, cheesema commented
Any reason that the windows builds shoudl be failing? I'm re-running the develop on the build to just see if it is a depedency change.

2022-01-05 17:29 UTC, joeljonsson commented
@cheesema the build errors were due to windows not supporting std::isnan for integer types. I simply removed this check from `compareMeshes` (1838fe6e61ab0bcdfec13958b79bc0dddcc6b600), as I don't think it's necessary.

2022-01-06 11:43 UTC, cheesema commented on test/MeshDataTest.cpp
> +    INSTANTIATE_TEST_SUITE_P(CopyData, MeshDataParameterTest, ::testing::Values<int>(6, 7, 10000));
What is the impact / reason for this change?

2022-01-06 11:45 UTC, cheesema reviewed
I would quickly like to run this locally and try before approval. 

@joeljonsson there is no current example showing the use of these right? Maybe we could create one?

2022-01-06 12:29 UTC, joeljonsson commented on test/MeshDataTest.cpp
> +    INSTANTIATE_TEST_SUITE_P(CopyData, MeshDataParameterTest, ::testing::Values<int>(6, 7, 10000));
Ah, good catch - I may have pushed this in haste.
*TEST_CASE_P has been deprecated in favor of *TEST_SUITE_P as of 1.10. We only require version 1.8.0 though, so this change might cause issues for versions <1.10. 

I guess there are 3 options
- revert to TEST_CASE_P and ignore the warning for newer versions
- keep TEST_SUITE_P and bump version requirement (and possibly the submodule)
- define a macro to switch between the two (provided there is a good way to check the gtest version)

2022-01-06 13:37 UTC, joeljonsson commented
@cheesema  I added a basic example, feel free to play around and edit it

2022-01-06 15:33 UTC, cheesema requested changes

2022-01-06 15:33 UTC, cheesema commented on examples/Example_lazy_access.cpp
> +    aprFile.open(file_name, "READ");
What are the requirements on this file? Does it work for you if you run it on the \LibAPR\test\files\Apr\large_low_cr\large_low_cr.apr test file? @joeljonsson 

I get the following errors from hdf5:

HDF5-DIAG: Error detected in HDF5 (1.12.0) thread 0:
  #000: C:\Users\bevan\APR\LibAPR\vcpkg\buildtrees\hdf5\src\df5-1_12_0-92e78e37d3.clean\src\H5Shyper.c line 10179 in H5S
select_hyperslab(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.0) thread 0:
  #000: C:\Users\bevan\APR\LibAPR\vcpkg\buildtrees\hdf5\src\df5-1_12_0-92e78e37d3.clean\src\H5Dio.c line

2022-01-06 15:33 UTC, cheesema commented on examples/Example_lazy_access.cpp
> +    aprFile.open(file_name, "READ");
For every loop.

2022-01-06 15:33 UTC, cheesema commented on examples/Example_lazy_access.cpp
> +    aprFile.open(file_name, "READ");
Same for sphere 120.

2022-01-06 16:13 UTC, joeljonsson commented on examples/Example_lazy_access.cpp
> +    aprFile.open(file_name, "READ");
It seems like those files have the particles field named 'particle_intensities' while we try to open 'particles'

2022-01-06 16:16 UTC, joeljonsson commented on examples/Example_lazy_access.cpp
> +    aprFile.open(file_name, "READ");
In this example there should be no extra requirement, but iterating lazily over the tree / tree particles of course requires that those structures exist in the file.

We should look over the error handling

2022-01-06 19:40 UTC, joeljonsson commented on examples/Example_lazy_access.cpp
> +    aprFile.open(file_name, "READ");
I added particle name detection and changed the init call to be more in line with our other classes.

But I went through the examples, and realized that we have some other problems with the I/O... For example, read_apr will fail if read_write_tree is true (default) but there is no tree structure. Example_get_apr produces files without the tree structure, but most examples try to read using default settings, resulting in errors.

2022-01-07 08:58 UTC, cheesema commented on test/MeshDataTest.cpp
> +    INSTANTIATE_TEST_SUITE_P(CopyData, MeshDataParameterTest, ::testing::Values<int>(6, 7, 10000));
Option 2 is probably the best forward looking bet?

What do you think.

2022-01-07 08:59 UTC, cheesema commented on examples/Example_lazy_access.cpp
> +    aprFile.open(file_name, "READ");
Yeah, I think we need to add the examples as part of the CI/CD, I think as we discussed a while ago, will ensure they stay fresh and help augment the tests.

On the particle names, good shout i've  been caught on that before, but I htink there is an updated method that just takes the particles regardless of name if there is only one?

2022-01-07 10:17 UTC, joeljonsson commented on examples/Example_lazy_access.cpp
> +    aprFile.open(file_name, "READ");
I removed the particle name specification from the examples, so that should be fine now.

Yes, we should get the examples tests running. But I think my biggest issue here is the I/O error handling (and the read_write_tree flag in general). Probably `read_apr` should simply read the APR, and the tree if it is available. The flag could be removed - writer functions could have `write_tree` as an input where appropriate, and open_time_point could try to open both apr and tree, and return codes to signal what is there, which reader functions can then use for error handling.

2022-01-07 13:30 UTC, joeljonsson commented on test/MeshDataTest.cpp
> +    INSTANTIATE_TEST_SUITE_P(CopyData, MeshDataParameterTest, ::testing::Values<int>(6, 7, 10000));
I agree - these changes are 3 years old, so there is probably no reason to support the old version. I added this

2022-01-07 14:44 UTC, cheesema commented on examples/Example_lazy_access.cpp
> +    aprFile.open(file_name, "READ");
I agree, the default case should just handle it, and then just allow optional settings for more complicated things.

I think I created all these things at the time when I was doing partial loading and utilisation of the trees ect for large datasets and controlling things at the low level, and didn't really think much about the classic case :P As in most cases. 

I ran into all these issues about a month ago to much confusion. I would say we leave that to a different PR however?

2022-01-07 15:48 UTC, joeljonsson commented on examples/Example_lazy_access.cpp
> +    aprFile.open(file_name, "READ");
Yeah let's post that as an issue and solve it later :-) From my side this is ready merge

2022-01-07 15:59 UTC, cheesema approved these changes
Awesome thanks Joel.

2022-01-07 15:59 UTC, merged