Few fixes for CUDA
AdaptiveParticles/LibAPR pull request #169
Opened 2022-04-19 14:28 UTC by krzysg

Hello,

Here are few fixes:
1. Removed 'extra_smooth' parameter as agreed with Joel some time ago (+/- 1 year ;-) ).
2. Added missing explicit instantiations for types needed by APRTest.cpp 
3. Switching off two big pipeline test - I will work on them in the near future and enable when whole pipeline is working again...
4. Because pipeline is not working I turned it off  in APRConverter.cpp (so CPU is always used regardless off APR_USE_CUDA). It allows to have working tests and progress on CUDA impl. 

Those changes allows to compile LibAPR and run tests for CUDA  which is minimum for later development and would be nice to have it on develop.

2022-04-20 11:08 UTC, joeljonsson commented
Thanks @krzysg !

The windows tests should pass after updating vcpkg (e.g. after #163 or #168 are merged in)

2022-04-20 11:09 UTC, joeljonsson requested changes

2022-04-20 11:09 UTC, joeljonsson commented on src/algorithm/APRConverter.hpp
> +#if true // #ifndef APR_USE_CUDA
I would suggest moving the GPU pipeline to a new method `APRConverter::get_apr_cuda` to make the difference more explicit and allow switching between the two

2022-04-21 09:07 UTC, joeljonsson commented
I'm thinking more along the lines of
```
public:
    void get_apr(...)         // CPU version

#ifdef APR_USE_CUDA
    void get_apr_cuda(...)    // CUDA version
#endif
```
such that both versions are callable by the user. This just requires the initial checks from `get_apr` to be moved into the cpu/gpu methods. Alternatively, if you want to keep the behavior of `get_apr` the way it is, you can make both `get_apr_cpu` and `get_apr_gpu` public in the same way, and then just alias `get_apr` to one of them based on cuda availability.

2022-04-21 11:28 UTC, krzysg commented
I think that get_apr should stay as it was in terms of behavior (so used pipeline should depend on APR_USE_CUDA value). 
I have change get_apr_cpu(cuda) to public so they can be used explicitly to force using specific pipeline.

2022-04-21 11:39 UTC, joeljonsson approved these changes

2022-04-21 11:41 UTC, joeljonsson commented
> I think that get_apr should stay as it was in terms of behavior (so used pipeline should depend on APR_USE_CUDA value). I have change get_apr_cpu(cuda) to public so they can be used explicitly to force using specific pipeline.

Excellent

2022-04-21 11:41 UTC, merged